/*VAL_PROFILE */
INSERT INTO VAL_PROFILE (PROFILE_ID, PLAYER_LEVEL, PLAYER_EXP, COINS, GEMS, HONOR_POINTS, NUM_OF_DECKS, STORY_PROGRESS , TIME_OF_CREATION, LAST_ACCESS_TIMESTAMP) VALUES (VAL_PROFILE_ID_SEQ.nextVal,1,0,100,5,200,3,0, SYSDATE, SYSDATE);

/*VAL_USER */
INSERT INTO VAL_USER  (USER_ID, USERNAME, PASSWORD, PROFILE_ID) VALUES (VAL_USER_ID_SEQ.nextVal,'testUser', 'qwerty', VAL_PROFILE_ID_SEQ.currVal);


/*VAL_TERRAIN */
INSERT INTO VAL_TERRAIN  (TERRAIN_ID, TERRAIN_NAME, IS_WALKABLE) VALUES (VAL_TERRAIN_ID_SEQ.nextVal,'grass', 'Y');
INSERT INTO VAL_TERRAIN  (TERRAIN_ID, TERRAIN_NAME, IS_WALKABLE) VALUES (VAL_TERRAIN_ID_SEQ.nextVal,'dirt', 'Y');
INSERT INTO VAL_TERRAIN  (TERRAIN_ID, TERRAIN_NAME, IS_WALKABLE) VALUES (VAL_TERRAIN_ID_SEQ.nextVal,'rock', 'Y');
INSERT INTO VAL_TERRAIN  (TERRAIN_ID, TERRAIN_NAME, IS_WALKABLE) VALUES (VAL_TERRAIN_ID_SEQ.nextVal,'water', 'N');

/*VAL_UNIT_TYPE*/
INSERT INTO VAL_UNIT_TYPE(UNIT_TYPE_CODE, UNIT_TYPE_NAME) VALUES ('CRSH', 'crush');
INSERT INTO VAL_UNIT_TYPE(UNIT_TYPE_CODE, UNIT_TYPE_NAME) VALUES ('SLSH','slash');
INSERT INTO VAL_UNIT_TYPE(UNIT_TYPE_CODE, UNIT_TYPE_NAME) VALUES ('PRCG','piercing');
INSERT INTO VAL_UNIT_TYPE(UNIT_TYPE_CODE, UNIT_TYPE_NAME) VALUES ('SHLD','shield');
INSERT INTO VAL_UNIT_TYPE(UNIT_TYPE_CODE, UNIT_TYPE_NAME) VALUES ('MGIC','magic');

/*VAL_CARD */
INSERT INTO VAL_CARD (CARD_ID, CARD_NAME) VALUES(VAL_CARD_ID_SEQ.nextVal, 'Test Unit');
INSERT INTO VAL_CARD (CARD_ID, CARD_NAME) VALUES(VAL_CARD_ID_SEQ.nextVal, 'Test Unit 2');
INSERT INTO VAL_CARD (CARD_ID, CARD_NAME) VALUES(VAL_CARD_ID_SEQ.nextVal, 'Test Unit 3');
INSERT INTO VAL_CARD (CARD_ID, CARD_NAME) VALUES(VAL_CARD_ID_SEQ.nextVal, 'Test Unit 4');
INSERT INTO VAL_CARD (CARD_ID, CARD_NAME) VALUES(VAL_CARD_ID_SEQ.nextVal, 'Test Unit 5');

/*VAL_UNIT */
INSERT INTO VAL_UNIT  (UNIT_ID, UNIT_NAME, UNIT_TYPE_CODE, UNIT_HP, UNIT_STR, UNIT_SPR, UNIT_AGI,UNIT_SPD) VALUES (VAL_UNIT_ID_SEQ.nextVal,'Test Unit','PRCG' ,10, 3, 5, 7, 5);
INSERT INTO VAL_UNIT  (UNIT_ID, UNIT_NAME, UNIT_TYPE_CODE, UNIT_HP, UNIT_STR, UNIT_SPR, UNIT_AGI,UNIT_SPD) VALUES (VAL_UNIT_ID_SEQ.nextVal,'Test Unit 2','SLSH' , 15, 5, 5, 5, 5);
INSERT INTO VAL_UNIT  (UNIT_ID, UNIT_NAME, UNIT_TYPE_CODE, UNIT_HP, UNIT_STR, UNIT_SPR, UNIT_AGI,UNIT_SPD) VALUES (VAL_UNIT_ID_SEQ.nextVal,'Test Unit 3','CRSH' , 20, 7, 2, 2, 5);
INSERT INTO VAL_UNIT  (UNIT_ID, UNIT_NAME, UNIT_TYPE_CODE, UNIT_HP, UNIT_STR, UNIT_SPR, UNIT_AGI,UNIT_SPD) VALUES (VAL_UNIT_ID_SEQ.nextVal,'Test Unit 4','SHLD' , 20, 7, 2, 2, 4);
INSERT INTO VAL_UNIT  (UNIT_ID, UNIT_NAME, UNIT_TYPE_CODE, UNIT_HP, UNIT_STR, UNIT_SPR, UNIT_AGI,UNIT_SPD) VALUES (VAL_UNIT_ID_SEQ.nextVal,'Test Unit 5','MGIC' , 20, 4, 7, 5, 5);

/*VAL_PROFILE_CARD */
INSERT INTO VAL_PROFILE_CARD (PROFILE_CARD_ID, PROFILE_ID, CARD_ID, DECK_CODE) VALUES (VAL_PROFILE_CARD_ID_SEQ.nextVal,881,1,1);
INSERT INTO VAL_PROFILE_CARD (PROFILE_CARD_ID, PROFILE_ID, CARD_ID, DECK_CODE) VALUES (VAL_PROFILE_CARD_ID_SEQ.nextVal,881,2,1);
INSERT INTO VAL_PROFILE_CARD (PROFILE_CARD_ID, PROFILE_ID, CARD_ID, DECK_CODE) VALUES (VAL_PROFILE_CARD_ID_SEQ.nextVal,881,3,1);
INSERT INTO VAL_PROFILE_CARD (PROFILE_CARD_ID, PROFILE_ID, CARD_ID, DECK_CODE) VALUES (VAL_PROFILE_CARD_ID_SEQ.nextVal,881,5,1);

/*VAL_DECK*/
UPDATE VAL_DECK SET DECK_LEADER_ID=2 WHERE DECK_ID = 1;
COMMIT;